package Chapter12.Test28;

/**
 * @author:YiMing
 * @create:2020/8/9,20:02
 * @version:1.0
 */
public class Test28 {
    public static void main(String[] args) {
            throw new MyException("出现了MyException异常");
    }
}
